name: real_image

# image_shape: [3, 1071, 1907]
image_shape: [3, 240, 320]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # camera_0:
    #   shape: ${task.image_shape}
    #   type: rgb
    image_1:
      shape: ${task.image_shape}
      type: rgb
    # camera_2:
    #   shape: ${task.image_shape}
    #   type: rgb
    image_2:
      shape: ${task.image_shape}
      type: rgb
    # camera_4:
    #   shape: ${task.image_shape}
    #   type: rgb
    joint_positions:
      shape: [7]
      type: low_dim
  action: 
    shape: [7]

task_name: &task_name lift
dataset_type: &dataset_type ph
dataset_path: &dataset_path /root/code/diffusion_policy/data/real/bc_data_il/gello_resize.h5
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02

